exec-once = hyprpaper
exec-once = waybar

exec-once = [workspace name:tg] Telegram
exec-once = [workspace name:tg] spotify
exec-once = [workspace name:browser] zen-browser

exec-once = mako
exec-once = exec-once = systemctl --user start hyprpolkitagent

exec-once = wl-paste --type text --watch cliphist store 
exec-once = wl-paste --type image --watch cliphist store 

exec-once = hypridle
