exec-once = hyprpaper
exec-once = waybar

exec-once = [workspace special:comms silent] Telegram
exec-once = [workspace special:spotify silent] spotify
exec-once = [workspace name:browser silent] zen-browser

exec-once = mako
exec-once = exec-once = systemctl --user start hyprpolkitagent

exec-once = wl-paste --type text --watch cliphist store 
exec-once = wl-paste --type image --watch cliphist store 

exec-once = hypridle
