# Global
windowrulev2 = suppressevent maximize,class:.*

# Rofi
windowrulev2 = stayfocused,class:^(Rofi)

# Zen browser
windowrulev2 = opacity 1 override,class:^(zen)
windowrulev2 = focusonactivate,class:^(zen)

# Picture-in-Picture
windowrulev2 = float, title:^(Picture-in-Picture)$
windowrulev2 = size 27%, title:(Picture-in-Picture)
windowrulev2 = pin, title:^(Picture-in-Picture)$
windowrulev2 = move 72.5% 72.3%, title:^(Picture-in-Picture)
windowrulev2 = nodim, title:^(Picture-in-Picture)
windowrulev2 = focusonactivate,class:^(firefox)

# Terminal
#windowrulev2 = float, class:^(kitty)
windowrulev2 = size 40% 50%, class:^(kitty)
windowrulev2 = opacity 1 override, class:^(kitty)

# File manager
windowrulev2 = float, class:^(thunar)
windowrulev2 = size 50%, class:^(thunar)

# Image and video viewers 
windowrulev2 = float,class:^(imv)$
windowrulev2 = center,class:^(imv)$
windowrulev2 = size 85%,class:^(imv)$
windowrulev2 = opacity 1 override,class:^(imv)
windowrulev2 = idleinhibit focus,class:^(imv)
windowrulev2 = float,class:^(mpv)$
windowrulev2 = center,class:^(mpv)$
windowrulev2 = size 85%,class:^(mpv)$
windowrulev2 = opacity 1 override,class:^(mpv)
windowrulev2 = idleinhibit focus,class:^(mpv)

windowrulev2 = workspace name:tg,class:^(org.telegram.desktop),title:^(Media viewer)
windowrulev2 = opacity 1 override,class:^(org.telegram.desktop),title:^(Media viewer)
windowrulev2 = float,class:^(org.telegram.desktop),title:^(Media viewer)
windowrulev2 = center,class:^(org.telegram.desktop),title:^(Media viewer)
windowrulev2 = size 85%,class:^(org.telegram.desktop),title:^(Media viewer)
windowrulev2 = suppressevent maximize,class:^(org.telegram.desktop),title:^(Media viewer)

# File picker
windowrulev2 = float,title:^(Choose Files)$
windowrulev2 = size 55% 70%,title:^(Choose Files)$

# Zoom
windowrulev2 = idleinhibit,class:^(zoom)
windowrulev2 = opacity 1 override,class:^(zoom)
windowrulev2 = stayfocused,class:(zoom),initialTitle:(menu window)
windowrulev2 = workspace name:meeting,class:^(zoom)

# Office
windowrulev2 = workspace name:documents,class:^(.*)(libreoffice)(.*)
windowrulev2 = opacity 1 override,class:^(.*)(libreoffice)(.*)

# Obsidian
windowrulev2 = workspace name:notes,class:^(obsidian)
windowrulev2 = focusonactivate,class:^(obsidian)

layerrule = blur, waybar
